In [5]:
import xgboost as xgb
import numpy as np 
import json
import pandas as pd

## *Load Old Model*

In [2]:
old_model = xgb.XGBRegressor()

In [4]:
old_model.load_model("C:/Users/amado/Desktop/Car-Predict-Price/app/xgb_car_price.json")

[10:38:34] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


## *Predictions*

In [9]:
df_inputs = pd.read_csv("C:/Users/amado/Desktop/Car-Predict-Price/data/inputs.csv")

In [10]:
X = np.asarray(df_inputs)

In [11]:
pred = old_model.predict(X)

In [12]:
df_inputs["predictions"] = pred

In [15]:
df_inputs.to_csv("C:/Users/amado/Desktop/Car-Predict-Price/data/predictions.csv",index = False)

## *New Predictions*

In [17]:
with open("C:/Users/amado/Desktop/Car-Predict-Price//app/columns.json") as json_file:
    
    columns = json.loads(json_file.read())
    columns = np.asarray(columns['columns_data'])

In [18]:
def predict(manufacturer,model,trasmision,year,fuel_type,engineSize,mileage,tax,mpg):
    
    data = np.zeros(len(columns))
    
    manufacturer_idx = np.where(columns == manufacturer)[0][0]
    model_idx = np.where(columns == model)[0][0]
    trasmision_idx = np.where(columns == trasmision)[0][0]
    fuel_type_idx = np.where(columns == fuel_type)[0][0]
    
    data[111] = year
    data[115] = engineSize
    data[116] = mileage
    data[117] = tax
    data[118] = mpg
    
    if manufacturer_idx >=0:
        data[manufacturer_idx] = 1

    if model_idx >=0:
        data[model_idx] = 1
        
    if trasmision_idx >=0:
        data[trasmision_idx] = 1
        
    if fuel_type_idx >=0:
        data[fuel_type_idx] = 1
        
    data = np.asarray([data])
    
    return old_model.predict(data)

### *Ford Mustang*

<img src = 'https://cdn.carbuzz.com/gallery-images/840x560/617000/300/617330.jpg' height ="100"  width ="600">
    

In [20]:
predict('Ford','Mustang','Automatic',2020,'Petrol',5.0,6000,145,22)

array([40409.504], dtype=float32)

### *Toyota Corolla*

<img src = 'https://images.kavak.services/images/30662/toyota-corolla-base2019-frontal-lateral-piloto-lejana-1608341522498.jpg?d=540x310'>

In [21]:
predict('Toyota','Corolla','Manual',2019,'Hybrid',2.0,5000,140,86.23)

array([22305.098], dtype=float32)

### *Hyundi GT86*

<img src = "https://e00-marca.uecdn.es/assets/multimedia/imagenes/2016/03/19/14583947669790.jpg" height = "600" width = "600">

In [22]:
predict('Hyundi','GT86','Manual',2016,'Petrol',2.0,50000,265,36.2)

array([14897.175], dtype=float32)

### *Audi A6*

<img src = "https://mediaservice.audi.com/media/fast/H4sIAAAAAAAAAFvzloG1tIiBOTrayfuvpGh6-m1zJgaGigIGBgZGoDhTtNOaz-I_2DhCHkCFmZQZWMpTkwoYgSrcmLgycxPTU_VBArz____nZ-RONNNNrSjRzUvNzWcHKhHkOb-ibkWM-qErHf7vJx24fn7uNOll1Qw833LNLySudV57OLXeI96WVUX5mNALBp5asf1a0768mrXrSWyTTPmWHSqVoXMYeOL8QvzWXLq5deKi3KDn-or7fThPeTLw7NJfYSp3q16zSKLhr_Gk9ZNr02qfM_BYPI6SXx0rfDPKXvqsY5aZS9C1V9sYeET0pxzNU9UwClaX6Nvax7Y2-eE7GQYejfM9j15lMnm9qBQ3lZRyVYoO-rCGgWeqrjkPax1f7dLkpcz1j0Qt3yvrz2PgUdvxwXKO5oV6uROCZQxGeQvMVB65MvBcUY1ozPHlk7_6mPPlg1lsjmb9-9kZeOYxftz_577AdIUlkj2vlghLm7y-r8DAc8J9b-X3eV_sudhjzj8XN3gcaMMTy8Czt0LxN0uchcDNJycud_49KZt-3UKQgeevYxGToqOfZnNJ0JeOZqMnygeqkhl4mN691j9lxcaxZOWU_Akbemt2vg8E-m3vzKNXvq4ROqz4TjhxjUHTwaKDu38xsAKjh3EdkGB-ByR4XYAEx0EGMAmKOBOQdByIz_qRmYGB24GBgS2EAQT4hEuLcgoSixJz9YpSiwvy84ozy1IFNQyIBMKsPo6RrkEAm9tGnFYCAAA?mimetype=image/png" width = 600>

In [26]:
predict('Audi','A6','Semi-Auto',2018,'Petrol',2.0,30000,150,55.4)

array([21410.787], dtype=float32)

### *Mercedes Benz G Class* 

<img src = 'https://acnews.blob.core.windows.net/imggallery/800x600/GAZ_836767a50d324bec83096120554e734f.jpg' width = 600>

In [27]:
predict('Mercedes','G Class','Automatic',2016,'Petrol',4.0,20000,325,30.4)

array([58324.824], dtype=float32)

### *BMW X7*

<img src = "https://cdn.motor1.com/images/mgl/lA08g/s1/bmw-x7.jpg" width = 600>

In [28]:
predict('BMW','X7','Semi-Auto',2019,'Diesel',3.0,6000,150,32)

array([69818.94], dtype=float32)

### *Toyota Yaris*

<img src = 'https://www.elcarrocolombiano.com/wp-content/uploads/2018/06/20180608-TOYOTA-YARIS-2019-BRASIL-01.jpg' width = 600>

In [29]:
predict('Toyota','Yaris','Manual',2019,'Hybrid',1.5,15000,140,76.3)

array([12424.653], dtype=float32)

### *Ford Focus*

<img src = "https://noticias.coches.com/wp-content/uploads/2014/07/ford_focus-3door-2008_r6.jpg" width = 600>

In [30]:
predict('Ford','Focus','Manual',2008,'Petrol',1.6,50000,20,68)

array([5222.1655], dtype=float32)